# Generated by Django 3.1.3 on 2020-12-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drafteados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.IntegerField(verbose_name='Pick')),
                ('nombreJugador', models.CharField(max_length=256, verbose_name='Nombre del Jugador')),
                ('universidad', models.CharField(max_length=256, verbose_name='Universidad')),
                ('posicionJugador', models.CharField(max_length=256, verbose_name='Posicion del Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEquipo', models.CharField(max_length=256, verbose_name='Nombre Equipo')),
                ('listaJugadores', models.TextField(verbose_name='Lista de Jugadores')),
                ('estadisticas', models.TextField(verbose_name='Estadisticas')),
                ('lesiones', models.TextField(verbose_name='Lesiones')),
                ('ranking', models.CharField(max_length=256, verbose_name='Ranking')),
                ('proxPartido', models.CharField(max_length=256, verbose_name='Proximo Partido')),
                ('sumaSalarios', models.IntegerField(verbose_name='Salario Total')),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJugador', models.CharField(max_length=256, verbose_name='Nombre del Jugador')),
                ('posicionJugador', models.CharField(max_length=256, verbose_name='Posicion del Jugador')),
                ('equipo', models.CharField(max_length=256, verbose_name='Equipo')),
                ('salario', models.IntegerField(verbose_name='Salario')),
            ],
        ),
    ]
