# Generated by Django 3.1.3 on 2020-12-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drafteados_equipo_jugadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='estadisticas',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='lesiones',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='listaJugadores',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='proxPartido',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='sumaSalarios',
        ),
    ]
