# Generated by Django 3.1.3 on 2020-12-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201225_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombreEquipo',
            field=models.TextField(unique=True, verbose_name='Nombre'),
        ),
    ]
