# Generated by Django 3.1.3 on 2020-12-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201225_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombreEquipo',
            field=models.CharField(max_length=256, unique=True, verbose_name='Nombre'),
        ),
    ]
