# Generated by Django 3.1.3 on 2020-12-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201225_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombreEquipo',
            field=models.TextField(verbose_name='Nombre'),
        ),
    ]
