# Generated by Django 3.1.3 on 2020-12-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201225_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombreEquipo',
            field=models.CharField(max_length=256, unique=True, verbose_name='Nombre'),
        ),
    ]
