# Generated by Django 3.1.3 on 2020-12-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201225_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombreEquipo',
            field=models.CharField(max_length=64),
        ),
    ]
