# Generated by Django 3.1.3 on 2020-12-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201226_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='proxPartido',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ranking',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
