# Generated by Django 3.1.3 on 2020-12-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201226_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='ranking',
            new_name='record',
        ),
    ]
