# Generated by Django 3.1.3 on 2020-12-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201226_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='record',
            new_name='ranking',
        ),
    ]
