# Generated by Django 3.1.3 on 2020-12-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201226_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='proxPartido',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ranking',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
