# Generated by Django 3.1.3 on 2020-12-25 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201226_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='proxPartido',
        ),
    ]
