# Generated by Django 3.1.3 on 2020-12-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_equipo_proxpartido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='ranking',
            field=models.CharField(default='nul', max_length=256),
        ),
    ]
