# Generated by Django 3.1.3 on 2020-12-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
