# Generated by Django 3.1.3 on 2020-12-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='proxPartido',
            field=models.CharField(default='nul', max_length=256),
        ),
    ]
