# Generated by Django 3.1.3 on 2020-12-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_equipo_proxpartido'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estadisticas',
            field=models.CharField(default='nul', max_length=256),
        ),
    ]
