# Generated by Django 3.1.3 on 2020-12-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_equipo_estadisticas'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='lesionados',
            field=models.CharField(default='nul', max_length=256),
        ),
    ]
