# Generated by Django 3.1.3 on 2020-12-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_equipo_lesionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='listaJugadores',
            field=models.CharField(default='nul', max_length=512),
        ),
    ]
