# Generated by Django 3.1.3 on 2020-12-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_equipo_listajugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='sumaSalarios',
            field=models.IntegerField(default=0),
        ),
    ]
