# Generated by Django 3.1.3 on 2020-12-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_equipo_sumasalarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJugador', models.CharField(max_length=64)),
                ('posicionJugador', models.CharField(default='nul', max_length=256)),
                ('nombreEquipo', models.CharField(default='nul', max_length=256)),
                ('salarioNumero', models.IntegerField(default=0)),
            ],
        ),
    ]
