# Generated by Django 3.1.3 on 2020-12-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nombreJugador',
            field=models.CharField(blank=True, default='nul', max_length=64, null=True),
        ),
    ]
