# Generated by Django 3.1.3 on 2020-12-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201227_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nombreJugador',
            field=models.CharField(default='nul', max_length=64),
        ),
    ]
