# Generated by Django 3.1.3 on 2020-12-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20201227_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drafteado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJugador', models.CharField(default='nul', max_length=64)),
                ('posicionJugador', models.CharField(default='nul', max_length=256)),
                ('universidad', models.CharField(default='nul', max_length=256)),
                ('pickJugador', models.IntegerField(default=0)),
            ],
        ),
    ]
