# Generated by Django 3.1.3 on 2020-12-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_drafteado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='nul', max_length=64)),
                ('enlace', models.CharField(default='nul', max_length=256)),
                ('contenido', models.TextField(default='nul')),
            ],
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombreEquipo',
            field=models.CharField(default='Draft 2021', max_length=256),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicionJugador',
            field=models.CharField(default='Draft 2021', max_length=256),
        ),
    ]
