# Generated by Django 3.1.3 on 2020-12-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20201228_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='asistenciasPorPartido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='puntoPorPartido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='rebotesPorPartido',
            field=models.IntegerField(default=0),
        ),
    ]
