# Generated by Django 3.1.3 on 2020-12-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20201230_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='puntoPorPartido',
            new_name='puntosPorPartido',
        ),
    ]
