# Generated by Django 3.1.3 on 2020-12-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20201230_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='asistenciasPorPartido',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='puntosPorPartido',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='rebotesPorPartido',
            field=models.FloatField(default=0.0),
        ),
    ]
