# Generated by Django 3.1.3 on 2020-12-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20201230_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagenJugador',
            field=models.CharField(default='nul', max_length=256),
        ),
    ]
