# Generated by Django 3.1.3 on 2020-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_equipo_logoequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagenNotica',
            field=models.CharField(default='nul', max_length=256),
        ),
    ]
