# Generated by Django 3.1.3 on 2020-12-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_noticia_imagennotica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='imagenNotica',
            new_name='imagenNoticia',
        ),
    ]
