# Generated by Django 3.1.3 on 2020-12-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafteado',
            name='posicionJugador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.posicion'),
        ),
    ]
