# Generated by Django 3.1.3 on 2020-12-30 16:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20201230_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafteado',
            name='posicionJugador',
            field=models.CharField(default='nul', max_length=64, verbose_name=main.models.Posicion),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='posicionNombre',
            field=models.CharField(max_length=256, verbose_name='Posición'),
        ),
    ]
