# Generated by Django 3.1.3 on 2020-12-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20201230_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='posicionJugador',
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicionJugador',
            field=models.ManyToManyField(to='main.Posicion'),
        ),
    ]
