# Generated by Django 3.1.3 on 2020-12-31 08:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20201230_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='posicionJugador',
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicionJugador',
            field=models.CharField(default='nul', max_length=64, verbose_name=main.models.Posicion),
        ),
    ]
