# Generated by Django 3.1.3 on 2021-01-10 15:54

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20201231_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicionDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicionNombre', models.CharField(max_length=256, verbose_name='PosiciónDraft')),
            ],
        ),
        migrations.AlterField(
            model_name='drafteado',
            name='posicionJugador',
            field=models.CharField(default='nul', max_length=64, verbose_name=main.models.PosicionDraft),
        ),
    ]
