# Generated by Django 3.1.3 on 2021-01-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20210110_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
