# Generated by Django 3.1.3 on 2021-01-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_delete_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNoticia', models.DateTimeField(default='20210101')),
                ('imagenNoticia', models.CharField(default='nul', max_length=256)),
                ('titulo', models.CharField(default='nul', max_length=64)),
                ('enlace', models.CharField(default='nul', max_length=256)),
                ('contenido', models.TextField(default='nul')),
            ],
        ),
    ]
