# Generated by Django 3.1.3 on 2021-01-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fechaNoticia',
            field=models.DateField(),
        ),
    ]
