# Generated by Django 3.1.3 on 2021-01-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20210112_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='fechaNoticia',
        ),
    ]
