# Generated by Django 3.1.3 on 2021-01-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_noticia_fechanoticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='id',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombreEquipo',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
