# Generated by Django 3.1.3 on 2021-01-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20210123_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
