# Generated by Django 3.1.3 on 2021-01-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_jugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='nombreEquipo',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
