# Generated by Django 3.1.3 on 2021-01-23 15:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20210123_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoEquipo', models.CharField(default='nul', max_length=256)),
                ('nombreEquipo', models.CharField(max_length=64)),
                ('ranking', models.CharField(default='nul', max_length=256)),
                ('proxPartido', models.CharField(default='nul', max_length=256)),
                ('estadisticas', models.CharField(default='nul', max_length=256)),
                ('lesionados', models.CharField(default='nul', max_length=256)),
                ('listaJugadores', models.CharField(default='nul', max_length=512)),
                ('sumaSalarios', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenJugador', models.CharField(default='nul', max_length=256)),
                ('nombreJugador', models.CharField(default='nul', max_length=64)),
                ('posicionJugador', models.CharField(default='nul', max_length=64, verbose_name=main.models.Posicion)),
                ('nombreEquipo', models.CharField(default='nul', max_length=256, verbose_name=main.models.Equipo)),
                ('salarioNumero', models.IntegerField(default=0)),
                ('puntosPorPartido', models.FloatField(default=0.0)),
                ('asistenciasPorPartido', models.FloatField(default=0.0)),
                ('rebotesPorPartido', models.FloatField(default=0.0)),
                ('per', models.FloatField(default=0.0)),
            ],
        ),
    ]
