# Generated by Django 3.1.3 on 2021-01-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_equipo_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nombreEquipo',
            field=models.ForeignKey(default='nul', max_length=256, on_delete=django.db.models.deletion.DO_NOTHING, to='main.equipo'),
        ),
    ]
