# Generated by Django 3.1.3 on 2021-01-24 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0059_auto_20210123_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntutacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(verbose_name='Puntuacion')),
                ('jugadorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jugador')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
