# Generated by Django 3.1.3 on 2021-01-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_puntutacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puntutacion',
        ),
    ]
