# Generated by Django 3.1.3 on 2021-01-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
