# Generated by Django 3.1.3 on 2021-01-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20210128_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafteado',
            name='universidad',
            field=models.CharField(default='nul', max_length=64),
        ),
        migrations.DeleteModel(
            name='Universidad',
        ),
    ]
