# Generated by Django 3.1.3 on 2021-01-28 15:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20210128_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafteado',
            name='universidad',
            field=models.CharField(default='nul', max_length=256, verbose_name=main.models.Universidad),
        ),
    ]
